import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node.js built-in modules (available on desktop via Electron, not on mobile)
    "fs",
    "path",
    "http",
    "https",
    "crypto",
    "os",
    "stream",
    "buffer",
    "events",
    ...builtins,
    // Note: busboy is NOT external - it needs to be bundled since it's an npm package
  ],
  platform: "browser", // Updated to browser platform
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  loader: {
    ".png": "dataurl",
    ".jpg": "dataurl",
    ".jpeg": "dataurl",
    ".svg": "dataurl",
    ".gif": "dataurl",
    ".webp": "dataurl",
  },
  plugins: [], // Removed inlineImage plugin to prevent copying image assets
  outfile: "main.js", // Updated to output to the root directory
});

if (prod) {
  console.log("Building production bundle...");
  await context.rebuild();
  console.log("Build complete.");
  process.exit(0);
} else {
  console.log("Starting esbuild in watch mode (dev)...");
  await context.watch();
}
